'use strict';

const DISCORD_URL = 'https://discord.gg/rEu5gvRBdM';
const YOUTUBE_URL = 'https://www.youtube.com/@eko8yildiz';

function renderAdvertisingLandingPage(user = null) {
  const accountLink = user
    ? '<a class="quiet-link" href="/dashboard">Paneline dön</a>'
    : '<a class="quiet-link" href="/login">Giriş yap</a>';

  const packages = [
    ['📱', 'Shorts & Hızlı Tanıtım', '30 TL', 'Dikey içerikte hızlı ve doğal marka görünürlüğü.', 'Başlangıç'],
    ['🎬', 'Uzun Video Sponsorluğu', '50 TL', 'Kalıcı alt bant, açıklama ve sabit yorum yerleşimi.', 'Süreklilik'],
    ['🎙️', 'Sesli Mid-Roll', '100 TL', 'Videonun akışına uyarlanan 20–30 saniyelik anlatım.', 'En çok tercih edilen'],
    ['🌟', 'Gold Kombin', '350 TL', 'Uzun video, Shorts ve topluluk paylaşımı birlikte.', 'Çok kanallı'],
    ['🚀', 'Mega Etkileşim', '500 TL', 'Video, Shorts, topluluk ve Discord duyurusu.', 'Tam kapsam'],
    ['💎', 'Çekilişli VIP', '670 TL', 'Mega kapsam ve topluluk odaklı çekiliş kurgusu.', 'Topluluk büyümesi'],
  ];

  const packageCards = packages.map(([icon, name, price, description, tag], index) => `
    <article class="price-card${index === 2 ? ' featured' : ''}">
      <div class="price-top"><span class="price-icon">${icon}</span><span class="tag">${tag}</span></div>
      <h3>${name}</h3><p>${description}</p>
      <div class="price"><strong>${price}</strong><span>net başlangıç fiyatı</span></div>
      <a href="/tickets/new?category=reklam">Bu paketi konuşalım <span aria-hidden="true">→</span></a>
    </article>`).join('');

  const faq = [
    ['Reklam doğrudan yayınlanıyor mu?', 'Hayır. Metin, görsel ve yerleşim önce sizinle netleştirilir; onayınızdan sonra yayın planına alınır.'],
    ['Fiyat neden izlenme başına hesaplanmıyor?', 'EkoYıldız paketleri yalnızca ham gösterimi değil; kurgu, yerleşim, topluluk dağıtımı, revize ve raporlama sürecini birlikte fiyatlandırır.'],
    ['Satış veya üye artışı garanti mi?', 'Her kampanyanın sonucu; teklifinize, kreatife ve kitle uyumuna göre değişir. Doğru formatı, doğal anlatımı ve ölçülebilir teslimi birlikte planlarız.'],
    ['Ödemeyi nasıl yapacağım?', 'Resmî siparişler yalnızca İtemSatış üzerinden yürütülür. Kişisel hesaba veya DM üzerinden ödeme istenmez.'],
  ].map(([question, answer]) => `<details><summary>${question}<span>+</span></summary><p>${answer}</p></details>`).join('');

  return `<!doctype html>
<html lang="tr">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <meta name="theme-color" content="#08090d">
  <meta name="robots" content="noindex,nofollow">
  <meta name="description" content="EkoYıldız YouTube ve Discord topluluğu için reklam ve sponsorluk seçeneklerini keşfedin.">
  <title>EkoYıldız Partner Studio — Reklam ve Sponsorluk</title>
  <style>
    :root{--bg:#08090d;--surface:#11131a;--surface-2:#171923;--text:#f7f7fb;--muted:#a5a8b4;--line:rgba(255,255,255,.11);--yellow:#ffd44a;--violet:#8075ff;--pink:#ff668f;--green:#73e2b2;--shadow:0 28px 80px rgba(0,0,0,.36)}
    *{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:var(--bg);color:var(--text);font:500 16px/1.6 Inter,ui-sans-serif,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;overflow-x:hidden}a{color:inherit}.shell{width:min(1180px,calc(100% - 40px));margin:auto}.ambient{position:fixed;inset:0;pointer-events:none;z-index:-1;overflow:hidden}.orb{position:absolute;border-radius:50%;filter:blur(90px);opacity:.17}.orb.one{width:520px;height:520px;background:#7165ff;left:-180px;top:-180px}.orb.two{width:470px;height:470px;background:#ff4e83;right:-190px;top:280px}.grid-noise{position:absolute;inset:0;background-image:linear-gradient(rgba(255,255,255,.022) 1px,transparent 1px),linear-gradient(90deg,rgba(255,255,255,.022) 1px,transparent 1px);background-size:48px 48px;mask-image:linear-gradient(to bottom,#000,transparent 75%)}
    .topbar{position:sticky;top:14px;z-index:50;width:min(1180px,calc(100% - 28px));margin:14px auto 0;padding:9px 12px 9px 14px;display:flex;align-items:center;justify-content:space-between;gap:16px;border:1px solid rgba(255,255,255,.22);border-radius:20px;background:radial-gradient(130% 120% at 50% -15%, rgba(255,255,255,.22) 0%, rgba(255,255,255,.05) 38%, rgba(139,92,246,.12) 70%, rgba(13,14,20,.78) 100%), linear-gradient(135deg, rgba(255,255,255,.12) 0%, rgba(17,19,30,.76) 100%);box-shadow:0 28px 64px -16px rgba(0,0,0,.55), 0 12px 26px -8px rgba(0,0,0,.35), inset 0 1.5px 1px rgba(255,255,255,.85), inset 0 3px 6px rgba(255,255,255,.25), inset 0 -1.5px 2px rgba(129,140,248,.38), inset 0 -3px 8px rgba(236,72,153,.18), 0 0 0 1px rgba(255,255,255,.18);backdrop-filter:blur(28px) saturate(220%) brightness(106%) contrast(104%);-webkit-backdrop-filter:blur(28px) saturate(220%) brightness(106%) contrast(104%);transition:all .25s cubic-bezier(0.34,1.56,0.64,1)}.topbar a,.topbar button{position:relative;transition:transform .22s cubic-bezier(0.34,1.56,0.64,1),box-shadow .2s ease,background .2s ease!important}.topbar a:active,.topbar button:active{transform:scale(0.935) translateY(2px)!important;transition:transform .06s cubic-bezier(0.1,0.9,0.2,1)!important;box-shadow:inset 0 2.5px 6px rgba(0,0,0,.5),inset 0 -1px 2px rgba(255,255,255,.4),0 0 18px rgba(139,92,246,.55)!important}.brand{display:flex;align-items:center;gap:10px;text-decoration:none;font-weight:900;letter-spacing:-.045em}.brand-mark{width:37px;height:37px;display:grid;place-items:center;flex:0 0 auto;border:1px solid rgba(255,255,255,.13);border-radius:12px;background:linear-gradient(145deg,#8a7eff,#ff6d99);box-shadow:inset 0 1px rgba(255,255,255,.32),0 8px 20px rgba(128,117,255,.22);color:white;font-size:.78rem;letter-spacing:-.07em}.brand i{font-style:normal;color:var(--pink)}.private-pill{font-size:.68rem;text-transform:uppercase;letter-spacing:.12em;color:#cfccd8;border:1px solid var(--line);border-radius:999px;padding:5px 8px;background:rgba(255,255,255,.045)}.top-actions{display:flex;align-items:center;gap:8px}.quiet-link{color:var(--muted);text-decoration:none;font-size:.8rem;font-weight:750;padding:9px 11px}.mini-cta,.button{display:inline-flex;align-items:center;justify-content:center;gap:8px;border-radius:11px;text-decoration:none;font-weight:850;transition:transform .2s ease,box-shadow .2s ease,background .2s ease}.mini-cta{padding:10px 14px;background:#fff;color:#111218;font-size:.8rem}.mini-cta:hover,.button:hover{transform:translateY(-2px)}
    .hero{min-height:760px;padding:115px 0 84px;display:grid;grid-template-columns:minmax(0,1.2fr) minmax(320px,.8fr);align-items:center;gap:64px}.eyebrow{display:inline-flex;align-items:center;gap:8px;color:#d8d5e2;font-size:.72rem;letter-spacing:.14em;text-transform:uppercase;font-weight:850}.eyebrow::before{content:"";width:7px;height:7px;border-radius:50%;background:var(--green);box-shadow:0 0 18px var(--green)}h1{max-width:800px;margin:20px 0 24px;font-size:clamp(3.4rem,7.6vw,7.4rem);line-height:.91;letter-spacing:-.083em}h1 span{display:block;background:linear-gradient(105deg,#fff 15%,#a99eff 55%,#ff88a9);-webkit-background-clip:text;color:transparent}.lead{max-width:690px;color:#c1c2cc;font-size:clamp(1rem,1.7vw,1.22rem);line-height:1.72}.hero-actions{display:flex;flex-wrap:wrap;gap:12px;margin-top:34px}.button{min-height:51px;padding:0 19px}.button.primary{background:#fff;color:#111218;box-shadow:0 14px 36px rgba(255,255,255,.12)}.button.secondary{border:1px solid var(--line);background:rgba(255,255,255,.055);color:#f3f2f7}.honesty{display:flex;align-items:flex-start;gap:9px;margin-top:22px;color:#858894;font-size:.78rem;max-width:620px}.honesty b{color:var(--green)}
    .signal-card{position:relative;border:1px solid var(--line);border-radius:26px;padding:22px;background:linear-gradient(145deg,rgba(255,255,255,.09),rgba(255,255,255,.025));box-shadow:var(--shadow),inset 0 1px rgba(255,255,255,.1);overflow:hidden}.signal-card::before{content:"";position:absolute;width:200px;height:200px;border-radius:50%;background:var(--violet);filter:blur(75px);opacity:.19;right:-60px;top:-70px}.signal-head{display:flex;justify-content:space-between;align-items:center;color:var(--muted);font-size:.76rem}.live{display:flex;align-items:center;gap:7px;color:var(--green)}.live::before{content:"";width:7px;height:7px;border-radius:50%;background:currentColor}.signal-main{padding:38px 0 26px}.signal-main small{color:var(--muted)}.signal-main strong{display:block;font-size:2.35rem;line-height:1.08;letter-spacing:-.055em;margin:7px 0}.signal-main p{margin:0;color:#c2c3cc;font-size:.87rem}.signal-list{display:grid;gap:8px}.signal-item{display:flex;justify-content:space-between;gap:18px;padding:13px;border-radius:12px;background:rgba(5,6,10,.34);border:1px solid rgba(255,255,255,.07);font-size:.82rem}.signal-item span{color:var(--muted)}.signal-item b{white-space:nowrap}.mascot-note{margin-top:12px;border:1px dashed rgba(255,212,74,.3);border-radius:12px;padding:12px;color:#d4ca9a;background:rgba(255,212,74,.045);font-size:.78rem}
    .trust-strip{display:grid;grid-template-columns:repeat(4,1fr);border-top:1px solid var(--line);border-bottom:1px solid var(--line)}.trust-item{padding:25px 20px;border-right:1px solid var(--line)}.trust-item:last-child{border:0}.trust-item strong{display:block;font-size:.88rem}.trust-item span{color:var(--muted);font-size:.76rem}
    section{padding:105px 0}.section-kicker{color:#988eff;font-size:.72rem;letter-spacing:.14em;text-transform:uppercase;font-weight:850}.section-head{display:grid;grid-template-columns:1fr 1fr;gap:50px;align-items:end;margin-bottom:42px}.section-head h2{max-width:680px;margin:10px 0 0;font-size:clamp(2.25rem,5vw,4.5rem);line-height:.98;letter-spacing:-.065em}.section-head p{color:var(--muted);margin:0;max-width:590px}.value-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}.value-card{min-height:270px;padding:25px;border:1px solid var(--line);border-radius:20px;background:linear-gradient(155deg,rgba(255,255,255,.065),rgba(255,255,255,.018));transition:transform .25s,border-color .25s}.value-card:hover{transform:translateY(-4px);border-color:rgba(128,117,255,.5)}.value-card .number{color:#777985;font-size:.72rem;font-weight:800}.value-card .icon{display:grid;place-items:center;width:43px;height:43px;border-radius:13px;background:rgba(128,117,255,.13);margin:34px 0 18px;font-size:1.2rem}.value-card h3{font-size:1.18rem;margin:0 0 9px;letter-spacing:-.035em}.value-card p{color:var(--muted);font-size:.87rem;margin:0}
    .price-section{padding-top:70px}.price-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}.price-card{position:relative;display:flex;flex-direction:column;min-height:330px;padding:23px;border:1px solid var(--line);border-radius:20px;background:var(--surface);overflow:hidden}.price-card.featured{border-color:rgba(128,117,255,.55);background:linear-gradient(150deg,rgba(128,117,255,.15),var(--surface) 52%)}.price-top{display:flex;align-items:center;justify-content:space-between}.price-icon{font-size:1.3rem}.tag{border:1px solid var(--line);border-radius:999px;padding:4px 8px;color:#c7c8d0;font-size:.65rem;font-weight:750}.price-card h3{margin:25px 0 8px;font-size:1.15rem;letter-spacing:-.035em}.price-card p{color:var(--muted);font-size:.85rem;margin:0}.price{margin:auto 0 17px;padding-top:30px}.price strong{display:block;font-size:2.15rem;letter-spacing:-.055em}.price span{color:var(--muted);font-size:.7rem}.price-card>a{display:flex;justify-content:space-between;align-items:center;padding-top:15px;border-top:1px solid var(--line);text-decoration:none;font-size:.79rem;font-weight:800;color:#e9e8ef}.pricing-note{margin:17px 0 0;color:#858894;font-size:.76rem}
    .why-price{display:grid;grid-template-columns:.9fr 1.1fr;gap:42px;align-items:center}.why-copy h2{font-size:clamp(2.4rem,5vw,4.8rem);line-height:.98;letter-spacing:-.07em;margin:10px 0 20px}.why-copy>p{color:var(--muted)}.cost-stack{display:grid;gap:10px}.cost-row{display:grid;grid-template-columns:44px 1fr auto;align-items:center;gap:14px;padding:17px;border:1px solid var(--line);border-radius:15px;background:rgba(255,255,255,.035)}.cost-row>span:first-child{display:grid;place-items:center;width:44px;height:44px;border-radius:12px;background:rgba(255,255,255,.055)}.cost-row strong{display:block;font-size:.88rem}.cost-row small{display:block;color:var(--muted)}.cost-row>em{font-style:normal;color:var(--green);font-size:.72rem;font-weight:800}
    .process{display:grid;grid-template-columns:repeat(4,1fr);gap:0;border:1px solid var(--line);border-radius:22px;overflow:hidden}.step{padding:26px;min-height:235px;border-right:1px solid var(--line);background:rgba(255,255,255,.025)}.step:last-child{border:0}.step b{color:#8f86ff;font-size:.75rem}.step h3{margin:38px 0 10px;font-size:1.04rem}.step p{margin:0;color:var(--muted);font-size:.82rem}.faq-layout{display:grid;grid-template-columns:.7fr 1.3fr;gap:60px}.faq-layout h2{font-size:clamp(2.4rem,4.5vw,4rem);line-height:1;letter-spacing:-.06em;margin:10px 0}.faq-layout>div>p{color:var(--muted)}details{border-top:1px solid var(--line)}details:last-child{border-bottom:1px solid var(--line)}summary{list-style:none;display:flex;justify-content:space-between;gap:20px;padding:22px 0;cursor:pointer;font-weight:800}summary::-webkit-details-marker{display:none}summary span{color:var(--muted);font-size:1.25rem;transition:transform .2s}details[open] summary span{transform:rotate(45deg)}details p{margin:-6px 0 23px;max-width:700px;color:var(--muted);font-size:.88rem}
    .final-cta{position:relative;margin:45px auto 25px;padding:clamp(40px,8vw,90px);border:1px solid var(--line);border-radius:30px;background:linear-gradient(135deg,rgba(128,117,255,.18),rgba(255,102,143,.09) 50%,rgba(255,255,255,.035));text-align:center;overflow:hidden}.final-cta::before{content:"";position:absolute;inset:0;background:radial-gradient(circle at 50% 0,rgba(255,255,255,.12),transparent 45%);pointer-events:none}.final-cta h2{position:relative;margin:0 auto 17px;max-width:850px;font-size:clamp(2.6rem,6vw,5.7rem);line-height:.95;letter-spacing:-.075em}.final-cta p{position:relative;color:#b9bac4;max-width:650px;margin:0 auto 30px}.final-cta .hero-actions{position:relative;justify-content:center;margin-top:0}.footer{display:flex;justify-content:space-between;gap:25px;padding:32px 0 46px;color:#777a85;font-size:.74rem}.footer a{text-decoration:none}.reveal{opacity:0;transform:translateY(16px);transition:opacity .7s ease,transform .7s ease}.reveal.visible{opacity:1;transform:none}
    @media(max-width:900px){.hero{grid-template-columns:1fr;padding-top:90px}.signal-card{max-width:620px}.section-head,.why-price,.faq-layout{grid-template-columns:1fr}.value-grid,.price-grid{grid-template-columns:repeat(2,1fr)}.process{grid-template-columns:repeat(2,1fr)}.step:nth-child(2){border-right:0}.step:nth-child(-n+2){border-bottom:1px solid var(--line)}.trust-strip{grid-template-columns:repeat(2,1fr)}.trust-item:nth-child(2){border-right:0}.trust-item:nth-child(-n+2){border-bottom:1px solid var(--line)}}
    @media(max-width:580px){.shell{width:min(100% - 26px,1180px)}.topbar{top:8px;margin-top:8px}.private-pill,.quiet-link{display:none}.hero{min-height:auto;padding:78px 0 65px;gap:40px}h1{font-size:clamp(3rem,15vw,4.7rem)}.hero-actions{flex-direction:column}.button{width:100%}.trust-strip,.value-grid,.price-grid,.process{grid-template-columns:1fr}.trust-item,.step{border-right:0;border-bottom:1px solid var(--line)}.trust-item:last-child,.step:last-child{border-bottom:0}.section-head{gap:18px}.footer{flex-direction:column}}
    @media(prefers-reduced-motion:reduce){html{scroll-behavior:auto}.reveal{opacity:1;transform:none;transition:none}.mini-cta,.button,.value-card{transition:none}}
  </style>
</head>
<body>
  <div class="ambient" aria-hidden="true"><div class="orb one"></div><div class="orb two"></div><div class="grid-noise"></div></div>
  <header class="topbar">
    <a class="brand" href="/"><span class="brand-mark" aria-hidden="true">E★</span><span>Eko<i>Yıldız</i></span><span class="private-pill">Partner Studio</span></a>
    <div class="top-actions">${accountLink}<a class="mini-cta" href="/tickets/new?category=reklam">Reklam talebi oluştur</a></div>
  </header>
  <main>
    <section class="hero shell">
      <div class="reveal"><span class="eyebrow">EkoYıldız Partner Studio · Özel bağlantı</span><h1>Reklam değil, <span>doğru toplulukla bağ.</span></h1><p class="lead">Roblox Türk topluluklarını gerçekten tanıyan bir YouTube kanalı, aktif bir Discord ekosistemi ve içeriğin akışını bozmayan reklam formatları. Mesajınızı yalnızca göstermeyelim; doğru bağlama yerleştirelim.</p><div class="hero-actions"><a class="button primary" href="/tickets/new?category=reklam">Bir kampanya planla <span>→</span></a><a class="button secondary" href="#paketler">Net fiyatları incele</a></div><div class="honesty"><b>✓</b><span>Şeffaflık notu: Kampanya sonuçları kitle ve kreatife göre değişir. Teslim kapsamını, yerleşimi ve raporlamayı baştan netleştiriyoruz.</span></div></div>
      <aside class="signal-card reveal"><div class="signal-head"><span>Kampanya sinyali</span><span class="live">Planlamaya açık</span></div><div class="signal-main"><small>Odak kitle</small><strong>Roblox Türkiye</strong><p>YouTube içeriği + Discord topluluğu + doğal anlatım</p></div><div class="signal-list"><div class="signal-item"><span>Yerleşim</span><b>İçeriğe uyumlu</b></div><div class="signal-item"><span>Onay süreci</span><b>Yayın öncesi</b></div><div class="signal-item"><span>Teslim</span><b>Raporlanabilir</b></div></div><div class="mascot-note">🌻 EkoMaskot diyor ki: “Reklamı videoya bantlamıyoruz; hikâyeye düzgünce oturtuyoruz.”</div></aside>
    </section>
    <div class="trust-strip shell reveal"><div class="trust-item"><strong>Niş topluluk</strong><span>Roblox ve topluluk kültürünü bilen izleyici</span></div><div class="trust-item"><strong>Çoklu dağıtım</strong><span>YouTube, Shorts, topluluk ve Discord</span></div><div class="trust-item"><strong>Önce onay</strong><span>Metin ve yerleşim yayın öncesi netleşir</span></div><div class="trust-item"><strong>Güvenli ödeme</strong><span>Yalnızca resmî İtemSatış süreci</span></div></div>

    <section class="shell">
      <div class="section-head reveal"><div><span class="section-kicker">Neden EkoYıldız’da reklam?</span><h2>İzleyici reklamı değil, bağlamı hatırlar.</h2></div><p>Genel kitleye rastgele gösterim yerine, Roblox topluluklarının dilini ve gündemini bilen bir içerik ekosisteminde görünürsünüz. Mesajınız formatın doğal bir parçası olacak şekilde planlanır.</p></div>
      <div class="value-grid">
        <article class="value-card reveal"><span class="number">01 / KİTLE</span><div class="icon">🎯</div><h3>Odaklı erişim</h3><p>Roblox oyuncuları, kamp yöneticileri ve Discord topluluklarıyla ilgilenen niş bir izleyici kitlesine konuşun.</p></article>
        <article class="value-card reveal"><span class="number">02 / ANLATIM</span><div class="icon">🎙️</div><h3>Doğal entegrasyon</h3><p>Kuru bir afiş yerine, videonun tonu ve izleyicinin beklentisiyle uyumlu metin ve yerleşim hazırlayın.</p></article>
        <article class="value-card reveal"><span class="number">03 / DAĞITIM</span><div class="icon">↗</div><h3>Tek içerikten fazlası</h3><p>İhtiyaca göre YouTube videosu, Shorts, topluluk gönderisi ve Discord duyurusunu aynı kampanyada birleştirin.</p></article>
        <article class="value-card reveal"><span class="number">04 / KONTROL</span><div class="icon">✓</div><h3>Yayın öncesi onay</h3><p>Marka adı, bağlantı, metin ve görsel yerleşimi sizin onayınız alınmadan yayına girmez.</p></article>
        <article class="value-card reveal"><span class="number">05 / RAPOR</span><div class="icon">▥</div><h3>Ölçülebilir teslim</h3><p>Nerede ve nasıl yayınlandığını görün; uygun paketlerde yayın sonrası performans çıktısını alın.</p></article>
        <article class="value-card reveal"><span class="number">06 / GÜVEN</span><div class="icon">🛡️</div><h3>Resmî sipariş akışı</h3><p>Teklif ve ödeme kaydı ticket üzerinden ilerler. Kişisel hesaba gönderim veya belirsiz DM ödemesi yoktur.</p></article>
      </div>
    </section>

    <section class="price-section shell" id="paketler">
      <div class="section-head reveal"><div><span class="section-kicker">Şeffaf paketler</span><h2>Üstü çizili fiyat yok. Numara yok.</h2></div><p>Her paket tek net başlangıç fiyatıyla gösterilir. Nihai kapsam; süre, yayın takvimi, üretim ihtiyacı ve ek dağıtım kanallarına göre ticket içinde yazılı biçimde onaylanır.</p></div>
      <div class="price-grid">${packageCards}</div><p class="pricing-note">Fiyatlar başlangıç paket kapsamını gösterir. Vergi, platform komisyonu veya özel üretim gereksinimleri teklif aşamasında açıkça belirtilir.</p>
    </section>

    <section class="shell why-price">
      <div class="why-copy reveal"><span class="section-kicker">Fiyatlar neden böyle?</span><h2>Gösterim değil, üretim ve yerleşim satın alırsınız.</h2><p>Bir reklamın değeri yalnızca ekranda kaldığı saniye değildir. Doğru cümle, doğru bağlam, yayın öncesi kontrol ve sonrasında doğrulanabilir teslim aynı sürecin parçalarıdır.</p><a class="button secondary" href="/tickets/new?category=reklam">Bütçeme göre planla →</a></div>
      <div class="cost-stack reveal"><div class="cost-row"><span>✦</span><div><strong>İçerik uyarlaması</strong><small>Mesajın EkoYıldız izleyicisine uygun dile çevrilmesi</small></div><em>Dahil</em></div><div class="cost-row"><span>🎬</span><div><strong>Üretim ve yerleşim</strong><small>Kurgu, seslendirme, görsel veya bağlantı konumlandırması</small></div><em>Dahil</em></div><div class="cost-row"><span>◎</span><div><strong>Yayın öncesi revize</strong><small>İsim, mesaj ve kreatif unsurların birlikte kontrolü</small></div><em>Dahil</em></div><div class="cost-row"><span>↗</span><div><strong>Topluluk dağıtımı</strong><small>Seçilen pakete göre YouTube, Shorts ve Discord desteği</small></div><em>Pakete göre</em></div><div class="cost-row"><span>▥</span><div><strong>Teslim kaydı</strong><small>Yayın bağlantıları ve uygun paketlerde performans özeti</small></div><em>Şeffaf</em></div></div>
    </section>

    <section class="shell">
      <div class="section-head reveal"><div><span class="section-kicker">Nasıl ilerliyor?</span><h2>Dört adımda yayına hazır.</h2></div><p>Uzun formlar ve belirsiz bekleyiş yerine, kararların ticket içinde görülebildiği kısa bir planlama akışı.</p></div>
      <div class="process reveal"><article class="step"><b>ADIM 01</b><h3>Hedefini anlat</h3><p>Topluluğunu, bağlantını, bütçeni ve ulaşmak istediğin kişiyi paylaş.</p></article><article class="step"><b>ADIM 02</b><h3>Formatı birlikte seç</h3><p>Shorts, video içi anlatım veya çoklu dağıtım arasından doğru kapsamı belirleyelim.</p></article><article class="step"><b>ADIM 03</b><h3>Metni onayla</h3><p>Yayın metni ve kreatif yerleşim açık biçimde sana sunulsun; gerekirse revize edilsin.</p></article><article class="step"><b>ADIM 04</b><h3>Yayın ve teslim</h3><p>Onaylanan takvimde yayınlansın, bağlantılar ve teslim bilgisi ticket’a eklensin.</p></article></div>
    </section>

    <section class="shell faq-layout"><div class="reveal"><span class="section-kicker">Kısa cevaplar</span><h2>Aklında soru kalmasın.</h2><p>Yine de kaldıysa ticket aç. Reklam ekibi “bu soru fazla detaylı” diye kaçmıyor — en fazla kahvesini tazeliyor.</p></div><div class="reveal">${faq}</div></section>

    <section class="final-cta shell reveal"><h2>Topluluğunu doğru yerde büyüt.</h2><p>Hazır bir paket seç veya bütçeni ve hedefini anlat; EkoYıldız reklam ekibi sana uygun kapsamı ticket içinde netleştirsin.</p><div class="hero-actions"><a class="button primary" href="/tickets/new?category=reklam">Reklam talebi oluştur →</a><a class="button secondary" href="${DISCORD_URL}" target="_blank" rel="noopener noreferrer">Discord’a katıl</a><a class="button secondary" href="${YOUTUBE_URL}" target="_blank" rel="noopener noreferrer">Kanalı incele ↗</a></div></section>
  </main>
  <footer class="footer shell"><span>© 2026 EkoYıldız Partner Studio · Özel bilgilendirme bağlantısı</span><span><a href="/safety">Safety Center</a> · <a href="/help">Help Center</a> · <a href="/anayasasi">Politikalar</a></span></footer>
  <script>(function(){const items=document.querySelectorAll('.reveal');if(!('IntersectionObserver'in window)){items.forEach(item=>item.classList.add('visible'));return}const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target)}}),{threshold:.12});items.forEach(item=>observer.observe(item))})();</script>
</body></html>`;
}

module.exports = { renderAdvertisingLandingPage, DISCORD_URL, YOUTUBE_URL };
