'use strict';

const authors = {
  'eko-safety': { slug: 'eko-safety', name: 'EkoYıldız Safety', role: 'Güvenlik ve topluluk ekibi', initials: 'ES', bio: 'Topluluğun güvenli kalması için rehberler, uyarılar ve şeffaflık raporları hazırlayan ekip.', mascot: 'safety', mascotName: 'Kalkanlı Eko', specialty: 'Hesap güvenliği · Safety Center', status: 'Şüpheli bağlantıları tarıyor.' },
  'deniz-kaya': { slug: 'deniz-kaya', name: 'Deniz Kaya', role: 'Topluluk Operasyonları', initials: 'DK', bio: 'Moderasyon süreçleri, üyelik deneyimi ve topluluk iletişimi üzerine çalışıyor.', mascot: 'community', mascotName: 'Topluluk Eko', specialty: 'Topluluk · Moderasyon süreçleri', status: 'Topluluktan güzel haberler topluyor.' },
  'arda-yilmaz': { slug: 'arda-yilmaz', name: 'Arda Yılmaz', role: 'Ürün ve Bot Ekibi', initials: 'AY', bio: 'EkoYıldız’ın botları, doğrulama akışları ve yeni ürün deneyimlerini geliştiriyor.', mascot: 'builder', mascotName: 'Üretici Eko', specialty: 'Botlar · Ürün notları', status: 'Yeni bir Phibi özelliğini test ediyor.' },
};

const posts = [
  { slug: 'yeni-moderasyon-araclari', category: 'Safety', date: '12 Eylül 2026', title: 'Daha güvenli bir topluluk için yeni moderasyon araçlarımız', excerpt: 'Yeni raporlama sistemi, vaka merkezi ve geliştirilmiş spam koruması yayında.', author: 'eko-safety', featured: true, body: ['Son aylarda moderasyon araçlarımızı daha anlaşılır ve daha hızlı hâle getirmek için çalışıyorduk. Bugün yeni raporlama sistemi, vaka merkezi ve geliştirilmiş spam korumasını kullanıma sunuyoruz.', 'Neler değişti? Daha hızlı raporlama, daha anlaşılır ceza nedenleri, yeni itiraz sistemi ve geliştirilmiş raid tespiti. Bu araçlar, kararların daha tutarlı alınmasına ve üyelerin süreci daha net izlemesine yardımcı olur.'] },
  { slug: 'report-sistemi-yenilendi', category: 'Güncellemeler', date: '04 Eylül 2026', title: 'Report sistemi yenilendi', excerpt: 'Bir kullanıcıyı bildirirken doğru bilgiyi vermek artık daha kolay.', author: 'deniz-kaya', body: ['Yeni bildirim akışı, olayın türünü seçmeyi ve açıklamayı ayırıyor. Böylece ekip doğru vakayı daha hızlı inceleyebiliyor.', 'Acil tehlike veya hesap güvenliği durumlarında önce Safety Center rehberlerini takip etmeni öneriyoruz.'] },
  { slug: 'moderasyon-sistemini-nasil-tasarladik', category: 'Behind the Scenes', date: '28 Ağustos 2026', title: 'Moderasyon sistemimizi nasıl tasarladık?', excerpt: 'Araçlardan önce ilkeleri, hızdan önce adaleti düşündük.', author: 'deniz-kaya', body: ['İyi bir moderasyon sistemi yalnızca ceza vermek için kurulmaz. Bağlamı görmek, üyeyi dinlemek ve kararın nedenini açıklamak için kurulur.', 'Bu nedenle işlem geçmişi, itiraz ve geri bildirim kanallarını aynı vaka akışında buluşturduk.'] },
  { slug: 'bot-v42-yayinlandi', category: 'Geliştirici', date: '20 Ağustos 2026', title: 'Bot v4.2 yayınlandı', excerpt: 'Daha hızlı olay işleme, net komut yanıtları ve yenilenmiş doğrulama akışı.', author: 'arda-yilmaz', body: ['v4.2 ile doğrulama, destek ve güvenlik akışlarını sadeleştirdik. Bot, üyeyi sadece doğru sayfaya yönlendirmekle kalmıyor; durumuna uygun bir sonraki adımı da gösteriyor.', 'Her yeni sürümde güvenlik ve veri minimizasyonu ilkelerini gözden geçiriyoruz.'] },
  { slug: 'bu-ay-toplulukta-neler-oldu', category: 'Topluluk', date: '15 Ağustos 2026', title: 'Bu ay toplulukta neler oldu?', excerpt: 'Etkinlikler, yeni partnerler ve üyelerden öne çıkan çalışmalar.', author: 'deniz-kaya', body: ['Bu ay etkinlik kanallarında yeni projeler, oyun geceleri ve topluluk tarafından hazırlanan çalışmalar öne çıktı.', 'Paylaşım yapan, yardım eden ve topluluğu iyi tutan herkese teşekkürler.'] },
  { slug: 'ban-affi-karari-neden-goruyorum', category: 'Safety', date: '13 Eylül 2026', title: 'Ban affı kararını neden görüyorum?', excerpt: 'Başvuruların nasıl incelendiği, ret kararının ne anlama geldiği ve hangi adımların uygun olduğu.', author: 'eko-safety', body: ['Ban affı başvuruları; verilen ilk yaptırım, başvurudaki açıklama, topluluk güvenliği ve önceki kararlar birlikte değerlendirilerek incelenir. Ret kararı, kullanıcıyı cezalandırmak için değil; kararın mevcut bilgilerle değiştirilemeyeceğini açıkça belirtmek için gönderilir.', 'İlk ret durumunda sistemin tanıdığı son başvuru hakkı varsa bunu dürüst, somut ve yeni bilgiyle kullanabilirsin. Nihai ret kararında ise aynı karar için tekrar başvuru açılmaz. Başvuru süreciyle ilgili genel bilgileri Safety Center’dan okuyabilir; teknik bir hata olduğunu düşünüyorsan destek talebi açabilirsin.'] },
  { slug: 'personel-sistemi-nasil-calisir', category: 'Topluluk', date: '13 Eylül 2026', title: 'Personel sistemimiz nasıl çalışır?', excerpt: 'Yetkili alımı, nöbet, geri bildirim ve ekipte gelişim için şeffaf bir rehber.', author: 'deniz-kaya', body: ['Personel sistemi, tek seferlik bir rol vermekten çok; üyelerin güvenli ve düzenli bir topluluk deneyimi sunmasına yardımcı olan sürekli bir gelişim akışıdır. Başvuru, tanışma, oryantasyon, görev ve geri bildirim adımlarını açık tutmaya çalışırız.', 'Bir görev veya geri bildirim bildirimi gördüğünde ne yapman gerektiğini ilgili rehber açıklar. Her durumda kararın gerekçesi, destek alınabilecek kanal ve ekipteki hakların net olmalıdır.'] },
  { slug: 'discord-ile-giris-nasil-calisir', category: 'Güvenlik', date: '13 Eylül 2026', title: 'Discord ile giriş nasıl çalışır?', excerpt: 'OAuth, DM kodu ve PIN ile giriş seçeneklerinin farkı; hangi bilgileri görürüz?', author: 'eko-safety', body: ['Discord ile girişte en hızlı seçenek OAuth’tur. Discord’un resmî izin ekranı üzerinden kimlik bilgisini doğrular; EkoYıldız Discord şifreni görmez veya saklamaz.', 'DM kodu ve komut PIN’i, OAuth kullanmak istemediğin durumlarda alternatif doğrulama yollarıdır. Kodlar yalnızca kısa süre için geçerlidir; hiçbir yetkili senden onları istemez.'] },
  { slug: 'roblox-hesabi-nasil-dogrulanir', category: 'Güvenlik', date: '13 Eylül 2026', title: 'Roblox hesabı nasıl doğrulanır?', excerpt: 'OAuth, arkadaş isteği ve profil açıklaması doğrulamasını güvenle kullanma rehberi.', author: 'eko-safety', body: ['Roblox doğrulaması hesabını topluluk rol ve özellikleriyle eşleştirmek için kullanılır. En hızlı yol Roblox OAuth’tur; Roblox parolan EkoYıldız’a gönderilmez.', 'OAuth kullanmak istemiyorsan yönetimin desteklediği arkadaş isteği veya profil açıklamasına geçici kod ekleme yöntemini kullanabilirsin. Şifreni, çerezini veya tokenını asla paylaşma.'] },
  { slug: 'cekilislere-guvenle-katilma-rehberi', category: 'Topluluk', date: '13 Eylül 2026', title: 'Çekilişlere güvenle nasıl katılırsın?', excerpt: 'Resmî çekilişleri ayırt et, görev sistemini anla ve ödül bahanesiyle yapılan dolandırıcılıklardan korun.', author: 'eko-safety', body: ['EkoYıldız çekilişleri yalnızca resmî site, duyuru kanalları ve doğrulanmış ekip hesapları üzerinden paylaşılır. Katılım için Discord veya Roblox şifresi, tarayıcı çerezi ya da token istenmez.', 'Görevleri tamamladığında biletlerin çekiliş profilinde görünür. Sonuçlar ve seçim süreci şeffaflık sayfasında yer alır. Ödül bahanesiyle seni başka bir siteye giriş yapmaya zorlayan bağlantılardan uzak dur.'] },
  { slug: 'phibi-destek-akisi', category: 'Güncellemeler', date: '12 Eylül 2026', title: 'Phibi ile destek akışı nasıl çalışıyor?', excerpt: 'Bildirim, destek ve yönlendirmelerin hangi durumda Phibi üzerinden iletildiğini açıklıyoruz.', author: 'arda-yilmaz', body: ['Phibi, EkoYıldız ekosistemindeki belirli destek ve güvenlik bildirimlerinde yardımcı iletişim katmanıdır. Amacı, doğru bilgiye doğru zamanda yönlendirmektir; hesap şifresi veya özel kod istemez.', 'Bir DM aldıysan gönderen hesabın resmîliğini kontrol et, kodunu kimseyle paylaşma ve şüpheli bir durumda Safety Center üzerinden rehbere ulaş.'] },
  { slug: 'yetkili-ekibinde-calismak', category: 'Topluluk', date: '11 Eylül 2026', title: 'EkoYıldız’da yetkili ekibinde çalışmak', excerpt: 'Esnek görev paylaşımı, öğrenme alanları, geri bildirim ve sağlıklı ekip iletişimi hakkında.', author: 'deniz-kaya', body: ['Yetkili ekibi, topluluğu düzenli tutmak için birlikte çalışan gönüllülerden oluşur. Başvuru sonrasında görevler, beklentiler ve iletişim kanalları açık biçimde paylaşılır.', 'Esnek görev saatleri, öğrenme fırsatları ve düzenli geri bildirim önemlidir. En iyi ekip deneyimi, rolün sınırlarının ve destek alınacak kişilerin net olduğu deneyimdir.'] },
  { slug: 'sponsorlu-baglantilari-nasil-inceliyoruz', category: 'Haberler', date: '10 Eylül 2026', title: 'Sponsorlu bağlantıları nasıl inceliyoruz?', excerpt: 'Toplulukta görünen sponsor kartları için açıklık, güvenlik ve bildirim ilkelerimiz.', author: 'eko-safety', body: ['Sponsorlu bir bağlantı gördüğünde bunun açıkça etiketlenmesini ve nereye götürdüğünün anlaşılır olmasını isteriz. Güvenlik açısından şüpheli, yönlendirmesi belirsiz veya yanıltıcı bağlantılar kaldırılır.', 'Bir sponsor kartında sorun fark edersen bağlantıyı paylaşmadan destek ekibine bildirebilirsin. Böylece ekip, kartı hızlıca inceleyip gerekli işlemi yapabilir.'] },
  { slug: 'phibi-bot-nasil-kullanilir', category: 'Dokümantasyon', date: '14 Eylül 2026', title: 'Phibi bot nasıl kullanılır?', excerpt: 'Komutlar, DM bildirimleri, destek yönlendirmeleri ve güvenli kullanım için başlangıç rehberi.', author: 'arda-yilmaz', body: ['Phibi, EkoYıldız topluluğunda destek ve bilgilendirme akışlarını kolaylaştırır. Komutları yalnızca resmî sunucuda kullan; bot senden parola, token veya giriş kodu istemez.', 'Bir işlemde yardıma ihtiyacın varsa önce komut yanıtındaki bağlantıyı oku. Sorun devam ederse ticket açarken hata mesajını ve ne yaptığını eklemen incelemeyi hızlandırır.'] },
  { slug: 'personel-mod-rehberi', category: 'Dokümantasyon', date: '14 Eylül 2026', title: 'Personel ve moderasyon rehberi', excerpt: 'Yetkili görevleri, olay bildirimi, destek talepleri ve sağlıklı moderasyon için temel ilkeler.', author: 'deniz-kaya', body: ['Personel araçları, üyeye yardımcı olmak ve topluluğu güvenli tutmak için vardır. Bir işlem yapmadan önce bağlamı incele, kararın nedenini açıkla ve gerektiğinde kıdemli yetkiliye aktar.', 'Destek taleplerinde kişisel veri veya özel kod isteme. Teknik hata varsa kullanıcıyı yardım merkezi ve hata sihirbazına yönlendir; tekrarlayan sorunları ekip kanalında belgeleyin.'] },
];

const safetyGuides = [
  {
    slug: 'discord-sahte-dm-ve-phishing', category: 'Discord güvenliği', icon: '🕵️', title: 'Sahte DM ve phishing bağlantılarını tanı', summary: 'Sahte Nitro, QR kod, token hırsızlığı ve kendini yetkili gibi gösteren hesaplara karşı uygulanabilir savunma rehberi.', mascot: 'Kalkanlı Eko diyor ki: “Bedava Nitro” bazen yalnızca pahalı bir baş ağrısıdır.', relatedSlugs: ['hesabimi-guvene-alma', 'kullanici-raporlama'],
    sections: [
      { title: 'Ne yapmalıyım?', body: 'Beklemediğin bir DM geldiğinde gönderen kişinin profilini, ortak sunucuları ve bağlantının gerçek alan adını ayrı ayrı kontrol et. Discord giriş ekranı gibi görünen sayfalara DM bağlantısından gitme; uygulamayı veya adresi kendin aç. Şifre, token veya doğrulama kodu istemeyiz.', steps: ['Mesajın ve profilin ekran görüntüsünü al.', 'Bağlantıya tıklamadan kullanıcıyı engelle ve Discord üzerinden bildir.', 'EkoYıldız yetkilisi olduğunu söylüyorsa resmî sunucudaki rolünü ayrıca kontrol et.'] },
      { title: 'Ne yapmamalıyım?', body: 'QR kod tarama, tarayıcı konsoluna kod yapıştırma, kullanıcı tokenını gönderme veya ekran paylaşırken giriş bilgilerini gösterme. Gerçek bir yetkili acele ettirerek hesabını doğrulamanı istemez; “şimdi yapmazsan ban” baskısı güvenilirlik işareti değil, kırmızı bayraktır.', steps: ['Mesajı arkadaşlarına test ettirme.', 'Şüpheli dosyayı indirip açma.', 'Kanıtları herkese açık kanalda kişisel bilgilerle paylaşma.'] },
      { title: 'Sonraki adım', body: 'Bir bilgi girdiysen Discord parolanı hemen değiştir, tüm cihazlardaki oturumları kapat, iki aşamalı doğrulamayı etkinleştir ve tanımadığın yetkili uygulamaları kaldır. Ardından kanıtlarıyla rapor oluştur; ödeme veya hesap kaybı varsa ilgili platformun resmî destek kanalına da başvur.', steps: ['Hesabı güvene alma rehberini tamamla.', 'EkoYıldız Safety ekibine rapor gönder.', 'Gerekirse yeni bir destek bileti aç.'] }
    ]
  },
  {
    slug: 'roblox-hesap-guvenligi', category: 'Roblox güvenliği', icon: '🎮', title: 'Roblox hesabını güvenle doğrula', summary: 'OAuth, arkadaş isteği ve profil açıklaması yöntemlerinin nasıl çalıştığını ve çerez hırsızlığından nasıl korunacağını öğren.', mascot: 'Üretici Eko notu: Robux sihir değildir; “bedava” düğmesi de genelde sihirbaz değildir.', relatedSlugs: ['discord-sahte-dm-ve-phishing', 'hesabimi-guvene-alma'],
    sections: [
      { title: 'Ne yapmalıyım?', body: 'Doğrulama için yalnızca EkoYıldız portalındaki resmî yöntemleri kullan. OAuth ekranında alan adını kontrol et; arkadaş isteği veya profil açıklaması yönteminde yalnızca sistemin verdiği geçici ifadeyi uygula. Roblox parolan portalımıza gelmez ve doğrulama tamamlandıktan sonra geçici açıklamayı kaldırabilirsin.', steps: ['Roblox kullanıcı adının doğru hesabı gösterdiğini kontrol et.', 'Mümkünse Roblox iki adımlı doğrulamayı aç.', 'Bağlı e-posta adresini güncel tut.'] },
      { title: 'Ne yapmamalıyım?', body: 'Kimseye `.ROBLOSECURITY` çerezini, tarayıcı depolama verisini, şifreni veya e-posta doğrulama kodunu gönderme. Ücretsiz Robux, grup rütbesi veya çekiliş ödülü bahanesiyle uzantı kurma. Bir yetkili bu bilgileri isterse rolü ne kadar parlak görünürse görünsün işlemi durdur.', steps: ['Bilinmeyen tarayıcı uzantısı kurma.', 'Ekran paylaşımında geliştirici araçlarını açma.', 'Hesap bağlantısını DM’de gönderilen kopya siteden yapma.'] },
      { title: 'Sonraki adım', body: 'Doğrulama başarısızsa aynı işlemi art arda tekrarlamak yerine kullanıcı adını ve seçtiğin yöntemi kontrol et. Sorun devam ederse hata metnini kopyala, yaklaşık saati belirt ve ticket sorun giderici üzerinden temiz bir destek talebi oluştur. Böylece ekip hangi aşamanın başarısız olduğunu görebilir.', steps: ['Portal oturumunu yenile.', 'Alternatif doğrulama yöntemini dene.', 'Hata koduyla destek bileti aç.'] }
    ]
  },
  {
    slug: 'youtube-topluluk-kurallari', category: 'YouTube ve topluluk', icon: '▶️', title: 'YouTube topluluğunda sağlıklı katılım', summary: 'Yorumlar, canlı yayınlar, eleştiri, içerik paylaşımı ve topluluk sınırları için sade davranış rehberi.', mascot: 'Topluluk Eko: Caps Lock bazen heyecandır; on satır sürerse küçük bir konser olabilir.', relatedSlugs: ['kullanici-raporlama', 'yetkiliyle-iletisim'],
    sections: [
      { title: 'Ne yapmalıyım?', body: 'Videoları, yayınları ve topluluk paylaşımlarını eleştirirken kişiye değil içeriğe odaklan. Farklı görüşlerin konuşulmasına izin ver, iddian varsa kaynağını açıkça belirt ve başkasının özel bilgisini paylaşma. Yayın sohbetinde moderasyon uyarısı aldıysan tartışmayı büyütmeden açıklamayı oku.', steps: ['Eleştiriyi somut ve anlaşılır yaz.', 'Spoiler veya hassas içerik için uyarı ekle.', 'İzinsiz kişisel bilgi görürsen raporla.'] },
      { title: 'Ne yapmamalıyım?', body: 'Hedef gösterme, tehdit, ayrımcı ifade, kişisel bilgi yayma, sahte kanıt üretme veya başka topluluklara toplu saldırı çağrısı yapma. Aynı mesajı tekrar tekrar göndermek görünürlüğü artırmaz; yalnızca sohbeti okunamaz hâle getirir ve moderasyon sürecini başlatabilir.', steps: ['Kavga için kullanıcı etiketleme.', 'Kırpılmış görüntüyü bağlamından koparma.', 'Moderasyon kararını başka kullanıcılara baskı aracı yapma.'] },
      { title: 'Sonraki adım', body: 'Rahatsız edici bir içerik gördüğünde bağlantıyı, video zaman damgasını ve kısa açıklamayı sakla. YouTube üzerindeki ihlali YouTube’a, EkoYıldız alanındaki topluluk ihlalini bize bildir. Acil fiziksel tehlike veya ciddi tehdit durumunda yalnızca topluluk ekibine güvenmek yerine güvendiğin bir yetişkine ve yerel mercilere ulaş.', steps: ['Platform raporlama aracını kullan.', 'Kanıtı değiştirmeden sakla.', 'Gerekirse EkoYıldız raporu oluştur.'] }
    ]
  },
  {
    slug: 'kullanici-raporlama', category: 'Raporlama', icon: '🚨', title: 'Bir kullanıcıyı doğru şekilde raporla', summary: 'Taciz, tehdit, reklam, sahte yetkili ve topluluk ihlallerinde incelemeyi hızlandıran kanıtları hazırla.', mascot: 'Kalkanlı Eko: 47 bulanık ekran görüntüsü yerine üç net kanıt çok daha atletiktir.', relatedSlugs: ['discord-sahte-dm-ve-phishing', 'ceza-ve-itiraz'],
    sections: [
      { title: 'Ne yapmalıyım?', body: 'Raporunda kim, ne yaptı, nerede oldu ve yaklaşık ne zaman gerçekleşti sorularını cevapla. Mesaj bağlantısını, kullanıcı kimliğini ve bağlamı gösteren ekran görüntülerini ekle. Kanıtın orijinal hâlini koru; kişisel verileri yalnızca inceleme için gerekli olduğunda ve güvenli destek kanalında paylaş.', steps: ['Olayı bir veya iki paragrafta özetle.', 'Mesaj bağlantılarını kronolojik sıraya koy.', 'Beklediğin çözümü açıkça belirt.'] },
      { title: 'Ne yapmamalıyım?', body: 'Topluluğu kullanıcıya karşı örgütleme, kanıtları düzenleyerek anlamını değiştirme veya aynı olay için çok sayıda bilet açma. Rapor göndermek otomatik ceza garantisi değildir; ekip kanıtı, bağlamı ve varsa önceki kayıtları birlikte değerlendirir. Yanlış bilgi süreci yavaşlatır.', steps: ['Herkese açık ifşa başlığı açma.', 'Başkasının hesabına girerek kanıt toplama.', 'Yetkiliden belirli bir ceza talep ederek baskı kurma.'] },
      { title: 'Sonraki adım', body: 'Rapor alındığında bir bilet numarası oluşur. Yetkili ek bilgi isterse yalnızca aynı vaka üzerinden yanıt ver. İnceleme sürerken kullanıcıyı engelleyebilir ve gizlilik ayarlarını sıkılaştırabilirsin. Sonuç paylaşımı, diğer kişilerin gizliliği nedeniyle her ayrıntıyı içermeyebilir.', steps: ['Bilet numaranı sakla.', 'Yeni kanıtı mevcut bilete ekle.', 'Yanıt bildirimlerini kontrol et.'] }
    ]
  },
  {
    slug: 'ceza-ve-itiraz', category: 'Moderasyon', icon: '⚖️', title: 'Ceza ve itiraz sürecini anla', summary: 'Bir kararın neden göründüğünü, hangi bilginin incelendiğini ve sağlıklı bir itirazın nasıl yazıldığını öğren.', mascot: 'Topluluk Eko: “Ama herkes yapıyor” bir savunma olabilir; güçlü bir kanıt sayılmaz.', relatedSlugs: ['kullanici-raporlama', 'yetkiliyle-iletisim'],
    sections: [
      { title: 'Ne yapmalıyım?', body: 'Önce bildirilen kuralı, işlem tarihini ve varsa vaka numarasını oku. İtirazında kararın hangi kısmının yanlış olduğunu, bunu destekleyen yeni bilgiyi ve olayın bağlamını açıkça yaz. Sorumluluk aldığın bir bölüm varsa dürüstçe belirtmek incelemeyi kolaylaştırır ve iletişimi daha sağlıklı tutar.', steps: ['Karar metnini tamamen oku.', 'Yeni ve doğrulanabilir kanıtı ekle.', 'Tek bir vaka üzerinden sakin biçimde iletişim kur.'] },
      { title: 'Ne yapmamalıyım?', body: 'Yetkililere toplu DM gönderme, tehdit etme, yeni hesapla cezayı aşma veya aynı metni farklı biletlerde tekrar gönderme. İtiraz, kararı veren kişiye karşı bir saldırı değil kararın yeniden incelenmesi talebidir. Sahte veya değiştirilmiş kanıt yeni bir ihlal olarak değerlendirilebilir.', steps: ['Kişisel hakaret kullanma.', 'Banı yan hesapla aşmaya çalışma.', 'Karar çıkmadan topluluk baskısı oluşturma.'] },
      { title: 'Sonraki adım', body: 'İtiraz alındıktan sonra karar onanabilir, değiştirilebilir veya ek bilgi istenebilir. Ret mesajında son başvuru hakkı belirtilmişse yalnızca yeni bilgiyle kullan. Teknik hata, yanlış kullanıcı eşleşmesi veya açılmayan bağlantı görürsen moderasyon kararından ayrı bir teknik destek bileti aç.', steps: ['İtiraz durumunu aynı sayfadan izle.', 'Ek bilgi talebine süre içinde yanıt ver.', 'Teknik sorunu ticket sihirbazına bildir.'] }
    ]
  },
  {
    slug: 'yetkiliyle-iletisim', category: 'Yetkili rehberi', icon: '🛡️', title: 'Yetkililerle güvenli ve verimli iletişim', summary: 'Resmî yetkiliyi tanı, doğru kanalı seç ve senden asla istenmemesi gereken bilgileri öğren.', mascot: 'Kalkanlı Eko: Yetkili rozeti iletişimi kolaylaştırır; telepati özelliği henüz eklenmedi.', relatedSlugs: ['kullanici-raporlama', 'ticket-sorun-giderici'],
    sections: [
      { title: 'Ne yapmalıyım?', body: 'Yetkilinin resmî sunucudaki rolünü kontrol et ve destek konularını mümkün olduğunca ticket üzerinden konuş. Sorunu kısa bir özet, hata metni ve beklediğin sonuçla anlat. Bir moderasyon görüşmesinde sakin kal, sorulara doğru bilgi ver ve anlamadığın karar gerekçesini açıklamasını iste.', steps: ['Doğru destek kategorisini seç.', 'Kişisel bilgileri gereksiz yere paylaşma.', 'Görüşme sonunda bilet numarasını sakla.'] },
      { title: 'Ne yapmamalıyım?', body: 'Yetkili olduğunu söyleyen kişiye şifre, token, tarayıcı çerezi, iki faktör kodu veya uzaktan erişim izni verme. EkoYıldız ekibi bu bilgileri istemez. Özel konuşmayı izinsiz yayımlama; tehdit, ısrarcı etiketleme veya farklı yetkililere aynı anda baskı yapma.', steps: ['AnyDesk benzeri erişim verme.', 'Kod veya çerez gönderme.', 'Acil olmayan konuda sürekli DM atma.'] },
      { title: 'Sonraki adım', body: 'Yanıt alamıyorsan mevcut bilete bir kez güncel bilgi ekle ve makul süre bekle. Bilet teknik olarak açılmıyorsa ticket sorun gidericiyi çalıştır. Bir yetkilinin davranışıyla ilgili şikâyetin varsa olayı o kişiye değil, denetim ekibine ve kanıtlarıyla bildir.', steps: ['Mevcut bilet durumunu kontrol et.', 'Teknik sihirbazı çalıştır.', 'Gerekirse yetkili davranışı raporu aç.'] }
    ]
  },
  {
    slug: 'ticket-sorun-giderici', category: 'Destek', icon: '🎫', title: 'Ticket hata sihirbazı', summary: 'Bilet açılmıyor, gönderimde kalıyor veya Discord kanalı görünmüyorsa sorunun hangi aşamada olduğunu bul.', mascot: 'Üretici Eko: Bileti üç kez tıklamak onu daha hızlı yapmaz; sadece üçüz yapabilir.', relatedSlugs: ['yetkiliyle-iletisim', 'hesabimi-guvene-alma'],
    sections: [
      { title: 'Ne yapmalıyım?', body: 'Önce sitede oturumunun açık olduğunu ve Discord hesabının doğru kullanıcıya bağlı göründüğünü kontrol et. Kategori seç, açıklamaya en az bir net cümle yaz ve gönder düğmesine bir kez bas. Sonuç kutusunda bilet numarası görünüyorsa kayıt alınmıştır; Discord teslimi sırada olsa bile tekrar bilet açma.', steps: ['Sayfayı bir kez yenileyip oturumu kontrol et.', 'Reklam engelleyici veya katı script engelini geçici test et.', 'Gösterilen bilet numarasını not al.'] },
      { title: 'Ne yapmamalıyım?', body: 'Gönder düğmesine art arda basma, aynı sorun için farklı kategorilerde bilet üretme veya hata metnini gizleyerek yalnızca “çalışmıyor” yazma. Tarayıcı konsolunda gördüğün token, çerez veya özel oturum değerlerini kimseye gönderme; yalnızca hata mesajı ve saat yeterlidir.', steps: ['Sayfa yüklenirken sekmeyi kapatma.', 'Özel oturum bilgisini ekran görüntüsüne alma.', 'Bilet numarası oluştuysa yeni kayıt açma.'] },
      { title: 'Sonraki adım', body: '“Discord’a teslim edildi” mesajını görürsen bilet Discord ekibine ulaşmıştır. “Teslim sırada” mesajında kayıt güvendedir ve bot yeniden erişilebilir olduğunda ekip web listesinden görebilir. Hiç bilet numarası oluşmazsa ekran görüntüsü, saat ve kullandığın cihazla teknik destek kanalına ulaş.', steps: ['Biletlerim sayfasında kaydı ara.', 'Teslim durumunu not et.', 'Kayıt yoksa teknik hata raporu gönder.'] }
    ]
  },
  {
    slug: 'hesabimi-guvene-alma', category: 'Hesap güvenliği', icon: '🔐', title: 'Hesabını ele geçirilme sonrası güvene al', summary: 'Discord veya Roblox hesabında şüpheli etkinlik fark ettiğinde ilk dakikalarda uygulanacak kurtarma adımları.', mascot: 'Kalkanlı Eko: Önce oturumları kapatıyoruz, sonra dedektif şapkasını takıyoruz.', relatedSlugs: ['discord-sahte-dm-ve-phishing', 'roblox-hesap-guvenligi'],
    sections: [
      { title: 'Ne yapmalıyım?', body: 'Temiz olduğuna güvendiğin bir cihazdan önce e-posta hesabının, ardından Discord veya Roblox hesabının parolasını değiştir. Tüm aktif oturumları kapat, iki aşamalı doğrulamayı aç ve bağlı uygulamalar ile tarayıcı uzantılarını incele. Kurtarma kodlarını çevrimdışı ve güvenli bir yerde sakla.', steps: ['E-posta güvenliğini önce tamamla.', 'Bilinmeyen oturum ve uygulamaları kaldır.', 'Cihazda güncel güvenlik taraması çalıştır.'] },
      { title: 'Ne yapmamalıyım?', body: 'Şüpheli cihazdan yeni parola oluşturma, saldırganla pazarlık yapma veya hesabı kurtarma vaadiyle para isteyen kişilere güvenme. EkoYıldız hesabını doğrudan geri veremez; Discord ve Roblox hesap kurtarma işlemleri yalnızca ilgili platformların resmî destek kanallarından yürütülür.', steps: ['Kurtarma kodlarını DM ile gönderme.', 'Aynı parolayı yeniden kullanma.', 'Sahte destek hesabına ödeme yapma.'] },
      { title: 'Sonraki adım', body: 'Hesabını güvene aldıktan sonra arkadaşlarına hesabından gönderilmiş şüpheli mesajları açmamalarını söyle ve platform desteğine olayın saatini bildir. EkoYıldız sunucusunda hesabından ihlal yapıldıysa kanıtlarla destek bileti aç; ekip topluluk içindeki etkileri ayrıca değerlendirebilir.', steps: ['Şüpheli mesajları bildirin.', 'Platform destek talebini sakla.', 'Topluluk etkisi için EkoYıldız bileti aç.'] }
    ]
  }
];

const topics = [
  ['Ticket Kullanımı', 'Destek', 'ticket-sorun-giderici'], ['Dolandırıcılıktan Korunma', 'Güvenlik', 'discord-sahte-dm-ve-phishing'], ['Sahte Personeller', 'Güvenlik', 'yetkiliyle-iletisim'], ['Ban Affı', 'Cezalar', 'ceza-ve-itiraz'], ['Moderasyon Kuralları', 'Moderasyon', 'ceza-ve-itiraz'], ['Personel İşlemleri', 'Yetkili rehberi', 'yetkiliyle-iletisim'], ['EkoYıldız Sistemleri', 'Destek', 'ticket-sorun-giderici'],
  ['Hesabımı nasıl korurum?', 'Güvenlik temelleri', 'hesabimi-guvene-alma'], ['2FA neden önemli?', 'Güvenlik temelleri', 'hesabimi-guvene-alma'], ['Şüpheli bağlantıya tıkladım', 'Hesap güvenliği', 'discord-sahte-dm-ve-phishing'], ['Hesabım ele geçirildi', 'Hesap güvenliği', 'hesabimi-guvene-alma'], ['Sahte botları nasıl anlarım?', 'Dolandırıcılık', 'discord-sahte-dm-ve-phishing'], ['Sahte Nitro bağlantıları', 'Dolandırıcılık', 'discord-sahte-dm-ve-phishing'], ['QR kod dolandırıcılığı', 'Dolandırıcılık', 'discord-sahte-dm-ve-phishing'], ['Token hırsızlığı', 'Dolandırıcılık', 'discord-sahte-dm-ve-phishing'], ['Sahte moderatörler', 'Dolandırıcılık', 'yetkiliyle-iletisim'], ['Bedava Robux dolandırıcılıkları', 'Dolandırıcılık', 'roblox-hesap-guvenligi'], ['Bir kullanıcıyı nasıl raporlarım?', 'Topluluk', 'kullanici-raporlama'], ['Taciz durumunda ne yapmalıyım?', 'Topluluk', 'kullanici-raporlama'], ['DM reklamlarını nasıl bildiririm?', 'Topluluk', 'kullanici-raporlama'], ['YouTube yorum kuralları', 'YouTube', 'youtube-topluluk-kurallari'], ['Moderasyon sistemimiz nasıl çalışıyor?', 'Moderasyon', 'ceza-ve-itiraz'], ['Neden ceza aldım?', 'Cezalar', 'ceza-ve-itiraz'], ['İtiraz nasıl yapılır?', 'Cezalar', 'ceza-ve-itiraz'], ['Bir yetkiliyle nasıl iletişim kurarım?', 'Destek', 'yetkiliyle-iletisim'], ['Ticket açılmıyor', 'Destek', 'ticket-sorun-giderici'], ['Ticket teslim durumları', 'Destek', 'ticket-sorun-giderici'],
];

const activeAlert = { date: '12 Eylül', title: 'Sahte Nitro bağlantılarında artış görüyoruz', text: 'Bilmediğiniz kişilerden gelen bağlantılara giriş yapmayın; resmî sayfa dışındaki QR kodları taramayın.' };
const pastAlerts = ['3 Eylül — QR giriş dolandırıcılığı', '27 Ağustos — Sahte moderatör hesapları'];

module.exports = { authors, posts, topics, safetyGuides, activeAlert, pastAlerts };
