'use strict';

const authors = {
  'eko-safety': { slug: 'eko-safety', name: 'EkoYıldız Safety', role: 'Güvenlik ve topluluk ekibi', initials: 'ES', bio: 'Topluluğun güvenli kalması için rehberler, uyarılar ve şeffaflık raporları hazırlayan ekip.', mascot: 'safety', mascotName: 'Kalkanlı Eko', specialty: 'Hesap güvenliği · Safety Center', status: 'Şüpheli bağlantıları tarıyor.' },
  'deniz-kaya': { slug: 'deniz-kaya', name: 'Deniz Kaya', role: 'Topluluk Operasyonları', initials: 'DK', bio: 'Moderasyon süreçleri, üyelik deneyimi ve topluluk iletişimi üzerine çalışıyor.', mascot: 'community', mascotName: 'Topluluk Eko', specialty: 'Topluluk · Moderasyon süreçleri', status: 'Topluluktan güzel haberler topluyor.' },
  'arda-yilmaz': { slug: 'arda-yilmaz', name: 'Arda Yılmaz', role: 'Ürün ve Bot Ekibi', initials: 'AY', bio: 'EkoYıldız’ın botları, doğrulama akışları ve yeni ürün deneyimlerini geliştiriyor.', mascot: 'builder', mascotName: 'Üretici Eko', specialty: 'Botlar · Ürün notları', status: 'Yeni bir Phibi özelliğini test ediyor.' },
};

const posts = [
  { slug: 'yeni-moderasyon-araclari', category: 'Safety', date: '12 Eylül 2026', title: 'Daha güvenli bir topluluk için yeni moderasyon araçlarımız', excerpt: 'Yeni raporlama sistemi, vaka merkezi ve geliştirilmiş spam koruması yayında.', author: 'eko-safety', featured: true, body: ['Son aylarda moderasyon araçlarımızı daha anlaşılır ve daha hızlı hâle getirmek için çalışıyorduk. Bugün yeni raporlama sistemi, vaka merkezi ve geliştirilmiş spam korumasını kullanıma sunuyoruz.', 'Neler değişti? Daha hızlı raporlama, daha anlaşılır ceza nedenleri, yeni itiraz sistemi ve geliştirilmiş raid tespiti. Bu araçlar, kararların daha tutarlı alınmasına ve üyelerin süreci daha net izlemesine yardımcı olur.'] },
  { slug: 'report-sistemi-yenilendi', category: 'Güncellemeler', date: '04 Eylül 2026', title: 'Report sistemi yenilendi', excerpt: 'Bir kullanıcıyı bildirirken doğru bilgiyi vermek artık daha kolay.', author: 'deniz-kaya', body: ['Yeni bildirim akışı, olayın türünü seçmeyi ve açıklamayı ayırıyor. Böylece ekip doğru vakayı daha hızlı inceleyebiliyor.', 'Acil tehlike veya hesap güvenliği durumlarında önce Safety Center rehberlerini takip etmeni öneriyoruz.'] },
  { slug: 'moderasyon-sistemini-nasil-tasarladik', category: 'Behind the Scenes', date: '28 Ağustos 2026', title: 'Moderasyon sistemimizi nasıl tasarladık?', excerpt: 'Araçlardan önce ilkeleri, hızdan önce adaleti düşündük.', author: 'deniz-kaya', body: ['İyi bir moderasyon sistemi yalnızca ceza vermek için kurulmaz. Bağlamı görmek, üyeyi dinlemek ve kararın nedenini açıklamak için kurulur.', 'Bu nedenle işlem geçmişi, itiraz ve geri bildirim kanallarını aynı vaka akışında buluşturduk.'] },
  { slug: 'bot-v42-yayinlandi', category: 'Geliştirici', date: '20 Ağustos 2026', title: 'Bot v4.2 yayınlandı', excerpt: 'Daha hızlı olay işleme, net komut yanıtları ve yenilenmiş doğrulama akışı.', author: 'arda-yilmaz', body: ['v4.2 ile doğrulama, destek ve güvenlik akışlarını sadeleştirdik. Bot, üyeyi sadece doğru sayfaya yönlendirmekle kalmıyor; durumuna uygun bir sonraki adımı da gösteriyor.', 'Her yeni sürümde güvenlik ve veri minimizasyonu ilkelerini gözden geçiriyoruz.'] },
  { slug: 'bu-ay-toplulukta-neler-oldu', category: 'Topluluk', date: '15 Ağustos 2026', title: 'Bu ay toplulukta neler oldu?', excerpt: 'Etkinlikler, yeni partnerler ve üyelerden öne çıkan çalışmalar.', author: 'deniz-kaya', body: ['Bu ay etkinlik kanallarında yeni projeler, oyun geceleri ve topluluk tarafından hazırlanan çalışmalar öne çıktı.', 'Paylaşım yapan, yardım eden ve topluluğu iyi tutan herkese teşekkürler.'] },
  { slug: 'ban-affi-karari-neden-goruyorum', category: 'Safety', date: '13 Eylül 2026', title: 'Ban affı kararını neden görüyorum?', excerpt: 'Başvuruların nasıl incelendiği, ret kararının ne anlama geldiği ve hangi adımların uygun olduğu.', author: 'eko-safety', body: ['Ban affı başvuruları; verilen ilk yaptırım, başvurudaki açıklama, topluluk güvenliği ve önceki kararlar birlikte değerlendirilerek incelenir. Ret kararı, kullanıcıyı cezalandırmak için değil; kararın mevcut bilgilerle değiştirilemeyeceğini açıkça belirtmek için gönderilir.', 'İlk ret durumunda sistemin tanıdığı son başvuru hakkı varsa bunu dürüst, somut ve yeni bilgiyle kullanabilirsin. Nihai ret kararında ise aynı karar için tekrar başvuru açılmaz. Başvuru süreciyle ilgili genel bilgileri Safety Center’dan okuyabilir; teknik bir hata olduğunu düşünüyorsan destek talebi açabilirsin.'] },
  { slug: 'personel-sistemi-nasil-calisir', category: 'Topluluk', date: '13 Eylül 2026', title: 'Personel sistemimiz nasıl çalışır?', excerpt: 'Yetkili alımı, nöbet, geri bildirim ve ekipte gelişim için şeffaf bir rehber.', author: 'deniz-kaya', body: ['Personel sistemi, tek seferlik bir rol vermekten çok; üyelerin güvenli ve düzenli bir topluluk deneyimi sunmasına yardımcı olan sürekli bir gelişim akışıdır. Başvuru, tanışma, oryantasyon, görev ve geri bildirim adımlarını açık tutmaya çalışırız.', 'Bir görev veya geri bildirim bildirimi gördüğünde ne yapman gerektiğini ilgili rehber açıklar. Her durumda kararın gerekçesi, destek alınabilecek kanal ve ekipteki hakların net olmalıdır.'] },
  { slug: 'discord-ile-giris-nasil-calisir', category: 'Güvenlik', date: '13 Eylül 2026', title: 'Discord ile giriş nasıl çalışır?', excerpt: 'OAuth, DM kodu ve PIN ile giriş seçeneklerinin farkı; hangi bilgileri görürüz?', author: 'eko-safety', body: ['Discord ile girişte en hızlı seçenek OAuth’tur. Discord’un resmî izin ekranı üzerinden kimlik bilgisini doğrular; EkoYıldız Discord şifreni görmez veya saklamaz.', 'DM kodu ve komut PIN’i, OAuth kullanmak istemediğin durumlarda alternatif doğrulama yollarıdır. Kodlar yalnızca kısa süre için geçerlidir; hiçbir yetkili senden onları istemez.'] },
  { slug: 'roblox-hesabi-nasil-dogrulanir', category: 'Güvenlik', date: '13 Eylül 2026', title: 'Roblox hesabı nasıl doğrulanır?', excerpt: 'OAuth, arkadaş isteği ve profil açıklaması doğrulamasını güvenle kullanma rehberi.', author: 'eko-safety', body: ['Roblox doğrulaması hesabını topluluk rol ve özellikleriyle eşleştirmek için kullanılır. En hızlı yol Roblox OAuth’tur; Roblox parolan EkoYıldız’a gönderilmez.', 'OAuth kullanmak istemiyorsan yönetimin desteklediği arkadaş isteği veya profil açıklamasına geçici kod ekleme yöntemini kullanabilirsin. Şifreni, çerezini veya tokenını asla paylaşma.'] },
  { slug: 'cekilislere-guvenle-katilma-rehberi', category: 'Topluluk', date: '13 Eylül 2026', title: 'Çekilişlere güvenle nasıl katılırsın?', excerpt: 'Resmî çekilişleri ayırt et, görev sistemini anla ve ödül bahanesiyle yapılan dolandırıcılıklardan korun.', author: 'eko-safety', body: ['EkoYıldız çekilişleri yalnızca resmî site, duyuru kanalları ve doğrulanmış ekip hesapları üzerinden paylaşılır. Katılım için Discord veya Roblox şifresi, tarayıcı çerezi ya da token istenmez.', 'Görevleri tamamladığında biletlerin çekiliş profilinde görünür. Sonuçlar ve seçim süreci şeffaflık sayfasında yer alır. Ödül bahanesiyle seni başka bir siteye giriş yapmaya zorlayan bağlantılardan uzak dur.'] },
  { slug: 'phibi-destek-akisi', category: 'Güncellemeler', date: '12 Eylül 2026', title: 'Phibi ile destek akışı nasıl çalışıyor?', excerpt: 'Bildirim, destek ve yönlendirmelerin hangi durumda Phibi üzerinden iletildiğini açıklıyoruz.', author: 'arda-yilmaz', body: ['Phibi, EkoYıldız ekosistemindeki belirli destek ve güvenlik bildirimlerinde yardımcı iletişim katmanıdır. Amacı, doğru bilgiye doğru zamanda yönlendirmektir; hesap şifresi veya özel kod istemez.', 'Bir DM aldıysan gönderen hesabın resmîliğini kontrol et, kodunu kimseyle paylaşma ve şüpheli bir durumda Safety Center üzerinden rehbere ulaş.'] },
  { slug: 'yetkili-ekibinde-calismak', category: 'Topluluk', date: '11 Eylül 2026', title: 'EkoYıldız’da yetkili ekibinde çalışmak', excerpt: 'Esnek görev paylaşımı, öğrenme alanları, geri bildirim ve sağlıklı ekip iletişimi hakkında.', author: 'deniz-kaya', body: ['Yetkili ekibi, topluluğu düzenli tutmak için birlikte çalışan gönüllülerden oluşur. Başvuru sonrasında görevler, beklentiler ve iletişim kanalları açık biçimde paylaşılır.', 'Esnek görev saatleri, öğrenme fırsatları ve düzenli geri bildirim önemlidir. En iyi ekip deneyimi, rolün sınırlarının ve destek alınacak kişilerin net olduğu deneyimdir.'] },
  { slug: 'sponsorlu-baglantilari-nasil-inceliyoruz', category: 'Haberler', date: '10 Eylül 2026', title: 'Sponsorlu bağlantıları nasıl inceliyoruz?', excerpt: 'Toplulukta görünen sponsor kartları için açıklık, güvenlik ve bildirim ilkelerimiz.', author: 'eko-safety', body: ['Sponsorlu bir bağlantı gördüğünde bunun açıkça etiketlenmesini ve nereye götürdüğünün anlaşılır olmasını isteriz. Güvenlik açısından şüpheli, yönlendirmesi belirsiz veya yanıltıcı bağlantılar kaldırılır.', 'Bir sponsor kartında sorun fark edersen bağlantıyı paylaşmadan destek ekibine bildirebilirsin. Böylece ekip, kartı hızlıca inceleyip gerekli işlemi yapabilir.'] },
];

const topics = [
  ['Hesabımı nasıl korurum?', 'Güvenlik temelleri'], ['2FA neden önemli?', 'Güvenlik temelleri'], ['Şüpheli bağlantıya tıkladım', 'Hesap güvenliği'], ['Hesabım ele geçirildi', 'Hesap güvenliği'], ['Sahte botları nasıl anlarım?', 'Dolandırıcılık'], ['Sahte Nitro bağlantıları', 'Dolandırıcılık'], ['QR kod dolandırıcılığı', 'Dolandırıcılık'], ['Token hırsızlığı', 'Dolandırıcılık'], ['Sahte moderatörler', 'Dolandırıcılık'], ['Bedava Robux dolandırıcılıkları', 'Dolandırıcılık'], ['Bir kullanıcıyı nasıl raporlarım?', 'Topluluk'], ['Taciz durumunda ne yapmalıyım?', 'Topluluk'], ['DM reklamlarını nasıl bildiririm?', 'Topluluk'], ['Raid nedir?', 'Moderasyon'], ['Şüpheli kullanıcıları nasıl bildiririm?', 'Moderasyon'], ['Moderasyon sistemimiz nasıl çalışıyor?', 'Moderasyon'], ['Neden ceza aldım?', 'Cezalar'], ['İtiraz nasıl yapılır?', 'Cezalar'], ['Ceza türleri nelerdir?', 'Cezalar'], ['Reportlar nasıl inceleniyor?', 'Cezalar'],
];

const activeAlert = { date: '12 Eylül', title: 'Sahte Nitro bağlantılarında artış görüyoruz', text: 'Bilmediğiniz kişilerden gelen bağlantılara giriş yapmayın; resmî sayfa dışındaki QR kodları taramayın.' };
const pastAlerts = ['3 Eylül — QR giriş dolandırıcılığı', '27 Ağustos — Sahte moderatör hesapları'];

module.exports = { authors, posts, topics, activeAlert, pastAlerts };
