/**
 * Mağaza ürünleri kataloğu.
 * type: "effect" | "badge" | "frame" | "color"
 */
const SHOP_ITEMS = [
  // ── Profil Efektleri ──────────────────────────────────────────────────────
  {
    id: "effect_aurora",
    name: "Aurora Efekti",
    desc: "Profilinde kuzey ışıkları animasyonu görünür.",
    icon: "🌌",
    type: "effect",
    price: 5000,
    cssClass: "effect-aurora",
    preview: "linear-gradient(135deg,#00c6ff,#0072ff,#7c6af7,#ff6bf7)",
  },
  {
    id: "effect_fire",
    name: "Ateş Efekti",
    desc: "Profilinde alev animasyonu görünür.",
    icon: "🔥",
    type: "effect",
    price: 4000,
    cssClass: "effect-fire",
    preview: "linear-gradient(135deg,#ff4e00,#ec9f05)",
  },
  {
    id: "effect_galaxy",
    name: "Galaksi Efekti",
    desc: "Profilinde yıldızlı galaksi animasyonu görünür.",
    icon: "✨",
    type: "effect",
    price: 7500,
    cssClass: "effect-galaxy",
    preview: "linear-gradient(135deg,#0f0c29,#302b63,#24243e)",
  },
  {
    id: "effect_neon",
    name: "Neon Efekti",
    desc: "Profilinde neon ışık efekti görünür.",
    icon: "💡",
    type: "effect",
    price: 3500,
    cssClass: "effect-neon",
    preview: "linear-gradient(135deg,#f953c6,#b91d73)",
  },
  {
    id: "effect_ocean",
    name: "Okyanus Efekti",
    desc: "Profilinde dalgalı okyanus animasyonu görünür.",
    icon: "🌊",
    type: "effect",
    price: 4500,
    cssClass: "effect-ocean",
    preview: "linear-gradient(135deg,#1a6b8a,#00b4d8,#90e0ef)",
  },
  {
    id: "effect_liquid",
    name: "Sıvı Cam (Liquid Glass)",
    desc: "Profilinde ışığı büken dinamik prizmatik sıvı cam dalgaları görünür.",
    icon: "💧",
    type: "effect",
    price: 6000,
    cssClass: "effect-liquid",
    preview: "radial-gradient(circle,rgba(255,255,255,0.8),rgba(124,106,247,0.4),rgba(56,189,248,0.2))",
  },
  {
    id: "effect_matrix",
    name: "Matrix Siber Kod",
    desc: "Profil kartında neon yeşil matrix kod akış aurası belirir.",
    icon: "💻",
    type: "effect",
    price: 5500,
    cssClass: "effect-matrix",
    preview: "linear-gradient(180deg,#00ff66,#052e16)",
  },
  {
    id: "effect_cosmic",
    name: "Kozmik Yıldız Tozu",
    desc: "Profilinde parıldayan yıldız tozu ve mor nebula aurası.",
    icon: "🌠",
    type: "effect",
    price: 7000,
    cssClass: "effect-cosmic",
    preview: "linear-gradient(135deg,#8b5cf6,#ec4899,#3b82f6)",
  },

  // ── Profil Çerçeveleri ────────────────────────────────────────────────────
  {
    id: "frame_gold",
    name: "Altın Çerçeve",
    desc: "Avatar etrafında altın renkli çerçeve.",
    icon: "🥇",
    type: "frame",
    price: 3000,
    cssClass: "frame-gold",
    preview: "#fbbf24",
  },
  {
    id: "frame_diamond",
    name: "Elmas Çerçeve",
    desc: "Avatar etrafında elmas parıltılı çerçeve.",
    icon: "💎",
    type: "frame",
    price: 8000,
    cssClass: "frame-diamond",
    preview: "linear-gradient(135deg,#a8edea,#fed6e3)",
  },
  {
    id: "frame_fire",
    name: "Ateş Çerçevesi",
    desc: "Avatar etrafında alev çerçevesi.",
    icon: "🔥",
    type: "frame",
    price: 5000,
    cssClass: "frame-fire",
    preview: "linear-gradient(135deg,#ff4e00,#ec9f05)",
  },
  {
    id: "frame_liquid",
    name: "Sıvı Kristal Mercek Çerçevesi",
    desc: "Avatar etrafında parlayan akışkan sıvı cam mercek çerçevesi.",
    icon: "🔮",
    type: "frame",
    price: 6500,
    cssClass: "frame-liquid",
    preview: "radial-gradient(circle,rgba(255,255,255,0.9),rgba(124,106,247,0.5))",
  },
  {
    id: "frame_cyber",
    name: "Siber Neon Nabız Çerçevesi",
    desc: "Avatar etrafında çift renkli dönen neon nabız halkası.",
    icon: "⚡",
    type: "frame",
    price: 6000,
    cssClass: "frame-cyber",
    preview: "linear-gradient(135deg,#00f2fe,#4facfe)",
  },
  {
    id: "frame_crown",
    name: "İmparatorluk Tacı Çerçevesi",
    desc: "Avatar etrafında parlayan altın taç ve asalet aurası.",
    icon: "👑",
    type: "frame",
    price: 9000,
    cssClass: "frame-crown",
    preview: "linear-gradient(135deg,#ffd700,#ffae19)",
  },
  {
    id: "frame_cosmic",
    name: "Kozmik Galaksi Çerçevesi",
    desc: "Avatar etrafında dönen yıldız tozu ve mor süpernova halkası.",
    icon: "🌌",
    type: "frame",
    price: 7500,
    cssClass: "frame-cosmic",
    preview: "linear-gradient(135deg,#7928ca,#ff0080)",
  },

  // ── Rozetler ──────────────────────────────────────────────────────────────
  {
    id: "badge_supporter",
    name: "Destekçi Rozeti",
    desc: "Profilinde 💜 Destekçi rozeti görünür.",
    icon: "💜",
    type: "badge",
    price: 2000,
    emoji: "💜",
    label: "Destekçi",
  },
  {
    id: "badge_veteran",
    name: "Veteran Rozeti",
    desc: "Profilinde ⚔️ Veteran rozeti görünür.",
    icon: "⚔️",
    type: "badge",
    price: 6000,
    emoji: "⚔️",
    label: "Veteran",
  },
  {
    id: "badge_star",
    name: "Yıldız Rozeti",
    desc: "Profilinde ⭐ Yıldız rozeti görünür.",
    icon: "⭐",
    type: "badge",
    price: 1500,
    emoji: "⭐",
    label: "Yıldız",
  },
  {
    id: "badge_crown",
    name: "Taç Rozeti",
    desc: "Profilinde 👑 Taç rozeti görünür.",
    icon: "👑",
    type: "badge",
    price: 10000,
    emoji: "👑",
    label: "Kral",
  },

  // ── Özel Renkler ──────────────────────────────────────────────────────────
  {
    id: "color_rainbow",
    name: "Gökkuşağı Rengi",
    desc: "Profil rengin gökkuşağı gradyanına dönüşür.",
    icon: "🌈",
    type: "color",
    price: 2500,
    value: "linear-gradient(135deg,#ff0000,#ff7700,#ffff00,#00ff00,#0000ff,#8b00ff)",
  },
  {
    id: "color_rose",
    name: "Gül Rengi",
    desc: "Profil rengin gül pembesi olur.",
    icon: "🌹",
    type: "color",
    price: 1000,
    value: "#e91e8c",
  },
  {
    id: "color_emerald",
    name: "Zümrüt Rengi",
    desc: "Profil rengin zümrüt yeşili olur.",
    icon: "💚",
    type: "color",
    price: 1000,
    value: "#10b981",
  },

  // ── Personel Retention & Özel Ürünler ────────────────────────────────────
  {
    id: "item_quest_skip",
    name: "Görev Pası Kartı (Quest Skip)",
    desc: "Sevmediğin veya vaktinin olmadığı 1 günlük görevi tek tıkla başarmış sayılma kartı.",
    icon: "🎫",
    type: "consumable",
    price: 1200,
  },
  {
    id: "item_custom_voice_channel",
    name: "Geçici Özel Ses Kanalı İzni",
    desc: "Sunucuda kendi belirleyeceğin isimle geçici özel ses kanalı açma hakkı.",
    icon: "🎙️",
    type: "perk",
    price: 2500,
  },
  {
    id: "item_custom_nick_color",
    name: "Özel Nickname Rengi & Rol Rozeti",
    desc: "Sunucu içi prestijli nickname rengi ve isminin yanına özel rol rozeti simgesi.",
    icon: "✨",
    type: "color",
    price: 3000,
  },
];

/** itemId'ye göre ürün bul */
function findItem(itemId) {
  return SHOP_ITEMS.find(i => i.id === itemId) || null;
}

module.exports = { SHOP_ITEMS, findItem };
